#!/usr/bin/env bash

function getFdCommand() {
    if command -v fd &> /dev/null; then
        echo "fd"
    elif command -v fdfind &> /dev/null; then
        echo "fdfind"
    else
        echo "fd is not installed"
        exit 1
    fi
}

function cds() {
    fd_cmd=$(getFdCommand)

    # Search for a path interactively
    selected=$($fd_cmd . "$HOME" --hidden | fzf)

    if [ ! -d $selected ]; then
        selected=$(dirname $selected)
    fi
    pushd $selected
}

