#!/usr/bin/env sh

# List paths
alias path="echo $PATH | tr ':' '\n'"

# Reload the shell (i.e. invoke as a login shell)
alias reload="exec ${SHELL} --login"

# Show and ignore first line of a pipe 
# https://unix.stackexchange.com/questions/28503/how-can-i-send-stdout-to-multiple-commands
alias header="tee >(head -n1) | tail -n+1"

# Show network files and their processes
# 1) -P inhibits the conversion of port numbers to port names for network files
# 2) -n inhibits the conversion of network numbers to host names for network files
alias netfiles="sudo lsof -i -P -n"
alias listen="netfiles | header | grep LISTEN"
alias estab="netfiles | header |grep ESTABILISHED"

# netstat (tcp, udp, listening, pid, numerical addresses)
alias procport="sudo netstat -tulpn"

# Show running deamons & services
# https://unix.stackexchange.com/questions/175380/how-to-list-all-running-daemons
# alias daemons="sudo systemctl --type=service"
# alias daemons="ps -C \"$(xlsclients | cut -d' ' -f3 | paste - -s -d ',')\" --ppid 2 --pid 2 --deselect -o tty,uid,pid,ppid,args | header | grep \"^?\""

